### ISSUE TITLE
请问onnx模型是如何导出的?

### ISSUE THREAD

**Issue by renshujiajia** [DakeQQ/Text-Similarity-NLU-for-Android#1]
我尝试在modelScope上进行onnx模型导出，系统提示不支持该模型导出为onnx，请问具体是怎么导出的呢？我现在希望将模型导出为onnx然后迁移到npu上去

**Comment by DakeQQ** [comment]
稍等一下, 明天晚上更新GTE的ONNX导出方法 :)

**Comment by DakeQQ** [comment]
导出方法已更新，请检查 'Export_ONNX' 文件夹。请注意，'attention_mask' 变量现在采用自定义格式。请查看注释和演示代码来了解使用方法。

**Comment by renshujiajia** [comment]
> 导出方法已更新，请检查 'Export_ONNX' 文件夹。请注意，'attention_mask' 变量现在采用自定义格式。请查看注释和演示代码来了解使用方法。

大佬神速，谢谢！我学习一下

**Comment by renshujiajia** [comment]
已经成功迁移到npu上，效果很ok，请问大佬这种导出模型的方式modeling_modified/model_bert.py是如何获取到的呢？希望能够学习到这种导出的工作流。

**Comment by DakeQQ** [comment]
1. 所有模型文件都来自官方脚本，例如 [Transformers GitHub 仓库](https://github.com/huggingface/transformers/tree/main/src/transformers/models)。
2. 接下来，使用调试模式逐步跟踪每一次前向(forward)调用。通常，第一个入口点位于 [module.py](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/module.py) 文件的第 1726 行（当前版本）: `result = self.forward(*input, **kwargs)`。你可以在第 1726 行设置断点，当调用 `torch.onnx.export()` 时，程序将会停下。
3. 请注意，您可能需要根据目标执行芯片（也称为后端）修改源代码。例如，NPU, GPU 和 NNAPI 通常不支持动态张量形状。Qualcomm HTP 甚至更加严格，它不支持 'Slice' ...操作符。
4. CPU 与其他芯片的通信会进一步减慢推理速度。因此，最好让所有算子在同一芯片上运行直到推理结束。

**Comment by renshujiajia** [comment]
> 1. 所有模型文件都来自官方脚本，例如 [Transformers GitHub 仓库](https://github.com/huggingface/transformers/tree/main/src/transformers/models)。
> 2. 接下来，使用调试模式逐步跟踪每一次前向(forward)调用。通常，第一个入口点位于 [module.py](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/module.py) 文件的第 1726 行（当前版本）: `result = self.forward(*input, **kwargs)`。你可以在第 1726 行设置断点，当调用 `torch.onnx.export()` 时，程序将会停下。
> 3. 请注意，您可能需要根据目标执行芯片（也称为后端）修改源代码。例如，NPU, GPU 和 NNAPI 通常不支持动态张量形状。Qualcomm HTP 甚至更加严格，它不支持 'Slice' ...操作符。
> 4. CPU 与其他芯片的通信会进一步减慢推理速度。因此，最好让所有算子在同一芯片上运行直到推理结束。

十分感谢！
